online_judge/blueprints/auth.py
import json
from flask import (render_template, Blueprint, request, session, current_app, redirect, url_for)

from online_judge.db.user import User
from online_judge.helpers.session import redirect_if_authenticated

auth = Blueprint('auth', __name__)

def validate_form():
    username = request.form['username']
    password = request.form['password']
    error = None

    if not username:
        error = json.dumps({'error': 'Username absent'})

    if not password:
        error = json.dumps({'error': 'Password absent'})

    return username, password, error

@auth.route('/', methods=['GET'])
@redirect_if_authenticated
def display_login_form():
    return render_template('login_register.html')

@auth.route('/login', methods=['POST'])
def login():
    username, password, error = validate_form()

    if error:
        return error, 400
    
    if not User.exists(username):
        return json.dumps({'error': 'Invalid credentials'}), 400

    user = User(username)

    if user.verify(password):
        session['username'] = username
        try:
            return redirect(request.args['next'])
        except KeyError:
            return redirect(url_for('home_page.display_problem_list'))
    else:
        return json.dumps({'error': 'Invalid credentials'}), 400

@auth.route('/signup', methods=['POST'])
def signup():
    username, password, error = validate_form()

    if error:
        return error, 400

    if User.exists(username):
        return json.dumps({'error': 'Username exists'}), 400
    else:
        User(username, password).save()
        return json.dumps({'status': 'success'}), 200

@auth.route('/logout', methods=['GET'])
def logout():
    current_app.session_interface.store.remove({'sid': session.sid})
    session.clear()
    return redirect(url_for('.display_login_form'))

online_judge/blueprints/home.py
import os
import requests

from flask import (render_template, redirect, url_for, request, Blueprint, session)

from online_judge.helpers.session import login_required

ALLOWED_EXTENSIONS = ['c', 'py', 'php']
APP_ROOT = os.path.dirname(os.path.abspath(__file__))
UPLOAD_FOLDER='{}/submissions'.format(APP_ROOT)

home_page = Blueprint('home_page', __name__, url_prefix='/home')

def allowed_files(filename):
    return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

def secure_filename(filename):
    return filename

def get_problems():
    problems = [
            {'title': 'Problem 1', 'text': '<p>Create a program to double the text in a file.</p><p><strong>Input: </strong>1 2 3 4</p><p><strong>Output: </strong>11 22 33 44</p>', 'id': 'Problem1'},
        {'title': 'Problem 2', 'text': 'Problem 2', 'id': 'Problem2'},
        {'title': 'Problem 3', 'text': 'Problem 3', 'id': 'Problem3'}
    ]
    return problems

def run_tests(code, lang):
    response = requests.post('http://smartypants.me:3000/test',
                  headers={'Content-Type': 'application/json'},
                  json={'code': code, 'email': 'temp@abc.com', 'language': lang, 'question': 1})
    return response.text, 200


@home_page.route('/', methods=['GET'])
@login_required
def display_problem_list():
    return render_template('home.html', problems=get_problems(), accepted_languages=ALLOWED_EXTENSIONS, username=session['username'])

@home_page.route('/', methods=['POST'])
@login_required
def submit_solution():
    '''
    try:
        submission = request.files['submission']
    except KeyError:
        return 'Empty File', 400

    if not submission.filename:
        return 'Empty File', 400

    if not allowed_files(submission.filename):
        return 'Incorrect file', 400

    filename = secure_filename(submission.filename)

    submission.save(os.path.join(UPLOAD_FOLDER, filename))
    '''

    code = request.form['code']

    language = request.form['lang']

    return run_tests(code, language)

    #return redirect(url_for('.home_get')) 

online_judge/db/__init__.py
from pymongo import MongoClient

HOST = 'localhost'
PORT = 27017
DBNAME = 'online_judge'

mongo_client = MongoClient(HOST, PORT)
db = mongo_client[DBNAME]

online_judge/templates/home.html
<html>
  <head>
    <title>Online Judge</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
    <link rel='stylesheet' href="{{ url_for('static', filename='vendor/codemirror/codemirror.css') }}">
  </head>
  <body>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <div class='container'>
      <div class='row'>
        <p class='pull-right'>{{ username }} | <a href="{{url_for('auth.logout')}}">Logout</a></p>
        <h2>Problem List</h2>
      </div>
      <div class='row'>
        <ul class='list-unstyled'>
          {% for problem in problems %}
            <li class='well'>
              <p class='lead'>{{ problem.title }}</p>
              <p>{{ problem.text|safe }}</p>

              <form method='POST' enctype='multipart/form-data'>
                <legend>Your solution</legend>
                <div class='form-group'>
                  <label for='code'>Type the code here:</label>
                  <textarea rows=10 name='code' class='form-control'></textarea>
                </div>
                <div class='form-group'>
                  <label for='lang'>Language:</label>
                  <select name='lang' class='form-control'>
                    {% for lang in accepted_languages%}
                    <option value='{{ lang }}'>{{ lang }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class='form-group'>
                  <label for='submission'>If uploading file, make sure to specify the correct extension.</label>
                  <input type='file' name='submission'>
                </div>
                <button type='submit' class='btn btn-primary'>Submit</button>
              </form>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <script src="{{ url_for('static', filename='vendor/codemirror/codemirror.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/codemirror/addon/mode/loadmode.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/codemirror/mode/meta.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/codemirror/mode/clike/clike.js')}}"></script>
    <script src='https://code.jquery.com/jquery-2.1.4.min.js'></script>
    <script>
      (function () {
        var codeTextAreas, editors, i, change;

        CodeMirror.modeURL = "{{url_for('static', filename='vendor/codemirror/mode')}}" + '/%N/%N.js';

        editors = [];

        config = {
          lineNumbers: true,
          mode: 'clike' 
        };

        jQuery('textarea.form-control').each(function () {
          editors.push({
            element: this,
            editor: CodeMirror.fromTextArea(this, config)
          })
        });
      
        jQuery('select.form-control').each(function () {
          CodeMirror.on(this, 'change', function (e) {
            change(this, e)
          });
        });

        change = function (selectElem, e) {
          var parentForm, closestTextarea, info, mode, spec, editor;

          parentForm = $(selectElem).closest('form'); 
          closestTextarea = $('textarea.form-control', parentForm)[0];
          info = CodeMirror.findModeByExtension(e.target.value);
          mode = info.mode;
          spec = info.mime;

          editor = editors.filter(function(editor) {
              return (editor.element === closestTextarea);
          })[0];

          editor.editor.setOption('mode', spec);
          CodeMirror.autoLoadMode(editor.editor, mode);
        };

      }());
    </script>
  </body>
</html>

online_judge/templates/login_register.html
<html>
  <head>
    <title>Online Judge</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
    <link rel='stylesheet' href="{{ url_for('static', filename='online_judge/main.css') }}">
    <script src='https://code.jquery.com/jquery-2.1.4.min.js'></script>
    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'></script>
  </head>
  <body>
    <div class='container'>
      <div class='row'>
        <div class='col-md-5 col-md-offset-3'>
          <h1 class='text-center'>Coding Challenge</h1>
        </div>
      </div>
      <div class='row center-align'>
        <div class='col-md-5 col-md-offset-3 well'>
          <ul class='nav nav-tabs'>
            <li role='presentation' class='active'>
              <a href='#login' id='login-tab' role='tab' data-toggle='tab'>Login</a>
            </li>
            <li role='presentation'>
              <a href='#signup' id='signup-tab' role='tab' data-toggle='tab'>Signup</a>
            </li>
          </ul>
          <div class='tab-content'>
            <div role='tabpanel' class='tab-pane fade in active' id='login'>
              <p>
                <form method='POST' action="{{ url_for('auth.login') }}">
                  <div class='form-group'>
                    <input type='email' class='form-control' name='username' placeholder='Your email address'>
                  </div>
                  <div class='form-group'>
                    <input type='password' class='form-control' name='password' placeholder='Your password'>
                  </div>
                  <button type='submit' class='btn btn-primary'>Log In</button>
                </form>
              </p>
            </div>
            <div role='tabpanel' class='tab-pane' id='signup'>
              <p>
                <form method='POST' action="{{ url_for('auth.signup') }}">
                  <div class='form-group'>
                    <input type='email' class='form-control' name='username' placeholder='Your email address'>
                  </div>
                  <div class='form-group'>
                    <input type='password' class='form-control' name='password' placeholder='Your password'>
                  </div>
                  <div class='form-group'>
                    <input type='password' class='form-control' placeholder='Confirm your password'>
                  </div>
                  <button type='submit' class='btn btn-primary'>Sign Up</button>
                </form>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>